#! /bin/bash



TARGET="$1"
BROWSER="firefox"
VERSION="1.0"
MAVI='\033[34m'
KIRMIZI='\033[31m'
YESIL='\033[32m'
SARI='\033[33m'
DELAY=5
RESET='\e[0m'

if [ -z $TARGET ]; then
	echo -e "$KIRMIZI 
	
░█▀▀█ ░█▀▀▀█ ░█▀▀█ 　 ░█─░█ ─█▀▀█ ░█▀▀█ ░█─▄▀ 
░█─▄▄ ░█──░█ ░█─▄▄ 　 ░█▀▀█ ░█▄▄█ ░█─── ░█▀▄─ 
░█▄▄█ ░█▄▄▄█ ░█▄▄█ 　 ░█─░█ ░█─░█ ░█▄▄█ ░█─░█$RESET"
	
	
	echo -e "$SARI --==[ https://www.marshackportal.tk ]==--$RESET"

        echo -e "$SARI --==[ goghack v$VERSION Coder By Mars ]==--$RESET"

	echo -e "$SARI --==[ Kullanım : ./hackggle <domain> ]==--$RESET"
        exit
fi


$BROWSER http://$TARGET 2> /dev/null
$BROWSER https://$TARGET 2> /dev/null

$BROWSER http://www.tcpiputils.com/browse/domain/$TARGET 2> /dev/null

$BROWSER http://toolbar.netcraft.com/site_report?url=$TARGET 2> /dev/null

$BROWSER https://www.shodan.io/search?query=$TARGET 2> /dev/null

$BROWSER https://www.censys.io/ipv4?q=$TARGET 2> /dev/null

$BROWSER https://crt.sh/?q=%25.$TARGET 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:zone-h.org+$TARGET" 2> /dev/null

$BROWSER "https://www.xssposed.org/search/?search=$TARGET&type=host" 2> /dev/null

$BROWSER "https://securityheaders.io/?q=$TARGET" 2> /dev/null

$BROWSER https://www.ssllabs.com/ssltest/analyze.html?d=$TARGET 2> /dev/null

$BROWSER https://securityheaders.io/?q=$TARGET 2> /dev/null

$BROWSER https://www.threatcrowd.org/domain.php?domain=$TARGET 2> /dev/null

$BROWSER https://www.zoomeye.org/searchResult/bugs?q=$TARGET 2> /dev/null

$BROWSER https://securitytrails.com/search/domain/$TARGET 2> /dev/null

$BROWSER https://web.archive.org/web/*/$TARGET 2> /dev/null

$BROWSER http://viewdns.info/reversewhois/?q=$TARGET 2> /dev/null

$BROWSER "https://www.punkspider.org/#searchkey=url&searchvalue=$TARGET&pagenumber=1&filterType=or" 2> /dev/null


sleep $DELAY

$BROWSER "http://www.google.ca/search?q=site:*.$TARGET" 2> /dev/null
$BROWSER "https://www.google.ca/search?q=site:*.*.$TARGET" 2> /dev/null

sleep $DELAY

$BROWSER "https://www.google.ca/search?q=site:$TARGET+username+OR+password+OR+login+OR+root+OR+admin" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:shell+OR+inurl:backdoor+OR+inurl:wso+OR+inurl:cmd+OR+shadow+OR+passwd+OR+boot.ini+OR+inurl:backdoor" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:readme+OR+inurl:license+OR+inurl:install+OR+inurl:setup+OR+inurl:config" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:wp-+OR+inurl:plugin+OR+inurl:upload+OR+inurl:download" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:$TARGET+inurl:redir+OR+inurl:url+OR+inurl:redirect+OR+inurl:return+OR+inurl:src=http+OR+inurl:r=http" 2> /dev/null


sleep $DELAY

$BROWSER "https://www.google.ca/search?q=site:$TARGET+ext:cgi+OR+ext:php+OR+ext:asp+OR+ext:aspx+OR+ext:jsp+OR+ext:jspx+OR+ext:swf+OR+ext:fla+OR+ext:xml" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:$TARGET+ext:doc+OR+ext:docx+OR+ext:csv+OR+ext:pdf+OR+ext:txt+OR+ext:log+OR+ext:bak" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:$TARGET+ext:action+OR+struts" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:pastebin.com+$TARGET" 2> /dev/null

$BROWSER "https://www.google.ca/search?q=site:linkedin.com+employees+$TARGET" 2> /dev/null
